### ISSUE TITLE
Left/Right transitions are not working properly on Android

### ISSUE THREAD

**Issue by rclai** [meteoric/contacts#1]
So I was testing this on my Android LG G3 and when I clicked on a contact, it didn't slide to the left, or right to go back to the list as shown in the browser version. Is this expected?

What happens is that the content goes away and the new content fades in. The blue header and background stay intact though.

**Comment by nickw** [comment]
@rclai I haven't actually tested on an Android device yet, just simulator. I was under the impression that it would work without a problem. Which Android version is your phone running?

**Comment by rclai** [comment]
Lollipop 4.4.2.

**Comment by nickw** [comment]
Ok thanks, I'll try to get my hands on a device to do some testing this week.

**Comment by nickw** [comment]
@rclai Do you get the same thing on the demo app? http://meteor-ionic.meteor.com/

**Comment by rclai** [comment]
I can see the left/right swipe more but there's still a fade out of the current content before the new content swipes in.

In the browser, there's a seamless transition that doesn't involve the fading out of the current content.

**Comment by nickw** [comment]
Closing this and moving it to meteoric/meteor-ionic#17
