### ISSUE TITLE
Android device

### ISSUE THREAD

**Issue by ghost** [meteoric/contacts#2]
meteor run android-device

Installing app on device...
Launching application...
LAUNCH SUCCESS
Command finished with error code 0: /meteor/contacts/.meteor/local/cordova-build/platforms/android/cordova/run --device
I20150112-18:04:19.846(6) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Error reading version file Error: Failed to resolve entry: file:///data/data/com.id1ptod1x1askkup8yb2pd/files/meteor/version
I20150112-18:04:19.912(6) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Couldn't load from the manifest, falling back to the bundled assets.
I20150112-18:04:20.126(6) (android:meteor_cordova_loader.js:12) METEOR CORDOVA DEBUG (meteor_cordova_loader.js) Loading from url: http://meteor.local

browser version works fine, without error

but on my device(GT-I9100, android 4.4.4), i see only bar-possitive and plus button, where is contacts? 

If i tuch + button > after  ~2-3 seconds latency with 0.1sec blank screen lag i see modal window...

Create Contact button change opacity after put and nothing happens.

**Comment by nickw** [comment]
I haven't done any testing on Android yet. I plan to acquire an Android device this week for that purpose. 

It sounds like we may have some performance issues with Android. Perhaps [using Crosswalk](https://meteor.hackpad.com/Building-Meteor-app-with-Crosswalk-kHKh4DzGxFQ) will be required to get decent performance.

**Comment by ghost** [comment]
When i use origin ionic, apps works fine, without lags and latency after click. i also use meteor-angular with meteor-ionic (https://github.com/Urigo/meteor-ionic) works fine but some trouble with double tap event.

**Comment by nickw** [comment]
Ok thanks, that's good to know.

**Comment by nickw** [comment]
It's running pretty well for me in the simulator, slightly laggy but hardly noticeable. But like I said, I'm working on getting a real device to test on this week.

![screen shot 2015-01-13 at 10 55 36 am](https://cloud.githubusercontent.com/assets/3907/5726771/d5a7112e-9b12-11e4-8f14-3218d7b6d401.png)

**Comment by nickw** [comment]
Closing this and consolidating all Android performance-related issues to meteoric/meteor-ionic#17.
