### ISSUE TITLE
Opening Application

### ISSUE THREAD

**Issue by alejandrogomez314** [meteoric/contacts#4]
After I clone the project into my computer "cd" into the file and hit "meteor", I get the following error:

While building the application:
   client/stylesheets/app.scss: Scss compiler error: undefined
   /Users/Alejo/Sites/meteorjs/contacts/client/stylesheets/app.scss:1: file to
   import not found or unreadable:
   '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic'
   Current dir: /Users/Alejo/Sites/meteorjs/contacts/client/stylesheets/

Why is this happening? Do I need to initialize a css compiler as well when running the app?

**Comment by nickw** [comment]
No that is expected due to a bug in the way Meteor handles assets from packages. Just re-run the server and it will work.

**Comment by alejandrogomez314** [comment]
Hit "meteor run" and it works!
