### ISSUE TITLE
run on ios

### ISSUE THREAD

**Issue by jeangui** [meteoric/contacts#8]
Hello,

I am trying to run the contact sample into the Ios Simulator and I get an error with thecom.ionic.keyboard@1.0.3 plugin.

`Error while running for mobile platforms: Error running                            
/Users/houitte/.meteor/packages/meteor-tool/.1.0.41.1orrphn++os.osx.x86_64+web.browser+web.cordova/meteor-tool-os.osx.x86_64/tools/cordova-scripts/cordova.sh
Error: version not found: 1.0.3 : com.ionic.keyboard/1.0.3
at RegClient.<anonymous>`

Should I install the plugin before running `meteor run ios` ?

I gonna test the other meteoric samples.

Thanks for the help.
@jeangui

**Comment by geritol** [comment]
same here

**Comment by nickw** [comment]
You probably need to update the version of `meteor-ionic`, check your `.meteor/versions` file and make sure it is using the latest.

**Comment by geritol** [comment]
I had the same with updated meteor ionic (v.0.1.16)

**Comment by jeangui** [comment]
the same here.
`meteoric:ionic@0.1.16` in .meteor/version
and
`Error: version not found: 1.0.3 : com.ionic.keyboard/1.0.3`

but I can see that the com.ionic.keyboard last version (https://github.com/driftyco/ionic-plugins-keyboard) is 1.0.4.

regards

**Comment by jeangui** [comment]
Finally by doing:

`meteor add cordova:com.ionic.keyboard@1.0.4`

I am able to build further the application but after I am blocked by another exception.

**Comment by jeangui** [comment]
Strange. I am getting the same error on the meteorhunt and the contact application but I don't get it on the demo application.

`ios: failed to start the app.                 
ENOENT, open '/Users/houitte/SANDBOX/METEOR/METEOR_IONIC/meteorhunt/.meteor/local/cordova-build/platforms/ios/cordova/console.log'``

I don't know what to do.

regards

**Comment by chalasr** [comment]
Maybe you need to give rights to all hidden folders (`sudo chmod -R 777 .*`)

**Comment by jeangui** [comment]
Hi chalasr
Finally I found out that i left a config.xml at the wrong place.
The issue should be closed.
Sorry.
Jeangui
