### ISSUE TITLE
@import '.meteor/local/build/...' not compatible with meteor build command

### ISSUE THREAD

**Issue by awatson1978** [meteoric/contacts#9]
Hi,

The following two lines in the [app.scss](https://github.com/meteoric/contacts/blob/master/client/stylesheets/app.scss#L3-4) file maybe aren't compatible with the `meteor build` command.  

``` scss
@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionic-sass/ionic';
@import '.meteor/local/build/programs/server/assets/packages/meteoric_ionicons-sass/ionicons';
```

In production environments, there's no guarantee that there's going to be a `.meteor/local` directory (there probably won't be).  
:(

**Comment by nickw** [comment]
Yeah there's doesn't seem to be a reliable way to include less/scss from a package in Meteor yet: https://meteor.hackpad.com/Improvements-to-LESS-and-other-CSS-preprocessors-fqDPbgOH8Fn

I'm open to suggestions…
